TOKEN:
WEBHOOK_URL:
SECRET_TOKEN:
DEV: # True or False
PGUSER:
PGPASSWORD:
PGPORT:
PGHOST:
PGDATABASE:
ADMIN_TG_ID: # Telegram user ID of the admin
SSL_KEYFILE: # Path to the SSL key file
SSL_CERTFILE: # Path to the SSL certificate file
TYPESENSE_API_KEY:
TYPESENSE_HOST:
