"""add source field to Station model

Revision ID: 6b3b7895d0a3
Revises: 484c6175c204
Create Date: 2023-07-19 11:13:29.032309

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6b3b7895d0a3'
down_revision = '484c6175c204'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('source', sa.String(), server_default='treni', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'source')
    # ### end Alembic commands ###
