"""remove codOrigine foreign key contraint

Revision ID: 6dfd121ad925
Revises: 737479d3f044
Create Date: 2023-07-17 10:59:37.269237

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '6dfd121ad925'
down_revision = '737479d3f044'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trains_codOrigine_fkey', 'trains', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('trains_codOrigine_fkey', 'trains', 'stations', ['codOrigine'], ['id'])
    # ### end Alembic commands ###
