"""remove region code

Revision ID: 737479d3f044
Revises: e062dcce3646
Create Date: 2023-07-17 10:39:59.903629

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '737479d3f044'
down_revision = 'e062dcce3646'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'region_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('region_code', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
