"""Remove unused fields in Postgres

Revision ID: 8975604fee40
Revises: 9cf53fbd990e
Create Date: 2023-09-14 14:50:14.143999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8975604fee40'
down_revision = '9cf53fbd990e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stop_times', 'ritardo_partenza')
    op.drop_column('stop_times', 'ritardo_arrivo')
    op.drop_column('stop_times', 'arrivo_reale')
    op.drop_column('stop_times', 'partenza_reale')
    op.drop_column('trips', 'statoTreno')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('statoTreno', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('stop_times', sa.Column('partenza_reale', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('stop_times', sa.Column('arrivo_reale', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('stop_times', sa.Column('ritardo_arrivo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stop_times', sa.Column('ritardo_partenza', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
