"""add times_count field to Station

Revision ID: c5dfc670b459
Revises: 6dfd121ad925
Create Date: 2023-07-18 14:27:33.240240

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c5dfc670b459'
down_revision = '6dfd121ad925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('times_count', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'times_count')
    # ### end Alembic commands ###
