"""create trenitalia tables

Revision ID: e062dcce3646
Revises: 
Create Date: 2023-07-16 21:25:11.557760

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e062dcce3646'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('region_code', sa.Integer(), nullable=False),
                    sa.Column('lat', sa.Float(), nullable=True),
                    sa.Column('lon', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('trains',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('codOrigine', sa.String(), nullable=False),
                    sa.Column('destinazione', sa.String(), nullable=False),
                    sa.Column('numeroTreno', sa.Integer(), nullable=False),
                    sa.Column('dataPartenzaTreno', sa.Date(), nullable=False),
                    sa.Column('statoTreno', sa.String(), nullable=False),
                    sa.Column('categoria', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['codOrigine'], ['stations.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('codOrigine', 'numeroTreno', 'dataPartenzaTreno')
                    )
    op.create_table('stop_times',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('train_id', sa.Integer(), nullable=False),
                    sa.Column('idFermata', sa.String(), nullable=False),
                    sa.Column('arrivo_teorico', sa.DateTime(), nullable=True),
                    sa.Column('arrivo_reale', sa.DateTime(), nullable=True),
                    sa.Column('partenza_teorica', sa.DateTime(), nullable=True),
                    sa.Column('partenza_reale', sa.DateTime(), nullable=True),
                    sa.Column('ritardo_arrivo', sa.Integer(), nullable=True),
                    sa.Column('ritardo_partenza', sa.Integer(), nullable=True),
                    sa.Column('binario', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['idFermata'], ['stations.id'], ),
                    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('train_id', 'idFermata')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stop_times')
    op.drop_table('trains')
    op.drop_table('stations')
    # ### end Alembic commands ###
