"""Change foreign key from stations to stops in StopTime

Revision ID: e07191853dcb
Revises: 9a2372c3d8a1
Create Date: 2023-09-14 15:28:32.017792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07191853dcb'
down_revision = '1b014925625b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stop_times_idFermata_fkey', 'stop_times', type_='foreignkey')
    op.create_foreign_key(None, 'stop_times', 'stops', ['stop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stop_times', type_='foreignkey')
    op.create_foreign_key('stop_times_idFermata_fkey', 'stop_times', 'stations', ['stop_id'], ['id'])
    # ### end Alembic commands ###
